### ISSUE TITLE
genres display

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51032-2019-Spring-Forum#10]
For genres, it's an array of strings which can be really long sometimes. Do we need to display all the genres in our detailed view? Can we just truncate it?

**Comment by susanstevens** [comment]
You should allow the label to wrap to a new line, rather than truncating the string. Setting the number of lines for a label to 0 will allow it to wrap to as many lines as are necessary.

Some books have long descriptions and titles, and you should also wrap these fields rather than truncating. In order to make all of the content visible (especially on smaller screens), you'll most likely need to embed everything in your detail view controller in a scroll view.

**Comment by jannydiu** [comment]
Got it! Thanks!
