### ISSUE TITLE
communicating between viewControllers

### ISSUE THREAD

**Issue by jannydiu** [uchicago-mobi/MPCS51032-2019-Spring-Forum#12]
I am trying using storyBoard.instantiateViewController(withIdentifier: ) method to communicate information between different viewControllers instead of delegate. Does that sound good?

**Comment by jannydiu** [comment]
I don't think this method works since it would create a new viewController every time it is called. I understand how delegate works for communication when there's a segue or indexPath, but I am not sure how that would work without segue, like the one in this assignment. Could you give some advice about how to communicate between viewControllers?

**Comment by susanstevens** [comment]
There are a number of different approaches you could take here, but this is my recommendation:

Create a class that has an array of book view models, maybe called `BookList` or something similar. In your AppDelegate's `didFinishLaunchingWithOptions` method, instantiate an instance of that class with an empty array. 

In the `didFinishLaunchingWithOptions` method, use the `window?.rootViewController` property to get a reference to the tab bar controller. Your goal here is to walk through the hierarchy of view controllers until you get a reference to the table view controller for each tab. Remember that the hierarchy is UITabBarController --> UINavigationController --> subclass of UITableViewController. 

Once you have a reference to each table view controller, set the `BookList` you just instantiated as a property on each one. Now, when one table view controller adds something to the list, the other table view controller will be able to see it.

The important thing here is that `BookList` needs to be a class (not a struct) so that the two table view controllers share a _reference_ to the same list. If it were a struct, they would each have separate copies of the list, and updates to the list wouldn't be shared between the tabs.

Let me know if that helps! We can also discuss this approach more in class on Wednesday.

**Comment by jannydiu** [comment]
That helps a lot! BTW, will this assignment due to tommorrow or it'll due to next week together with the other part of this project?

**Comment by susanstevens** [comment]
Great! It will be due next Wednesday (4/24). You don't need to submit anything tomorrow.
