### ISSUE TITLE
Intents UI Extension Not Being Rendered

### ISSUE THREAD

**Issue by carterperrin** [uchicago-mobi/MPCS51032-2019-Spring-Forum#22]
I've set up my UI Extension but the `configureView` method doesn't seem to be getting called at all (nothing prints to the console and my breakpoints aren't getting hit). As a result, my view doesn't appear.

I have added the supported intents to my UI Extension `info.plist` and haven't change the default name of my `UIViewController`. Is anyone else running into this or have any ideas on what I could be doing wrong?

**Comment by susanstevens** [comment]
Here's one thing to check: In your project file, if you select your main app's target and go to the "General" tab, you should see a section called "Embedded Binaries" (under "App Icons and Launch Images"). Does it list both of your extensions? If not, try clicking on the plus button to add whatever's missing.

You might also want to give this method a try, instead of `configureView`:

```swift
func configure(with interaction: INInteraction,
                   context: INUIHostedViewContext,
                   completion: @escaping (CGSize) -> Void)
```
