### ISSUE TITLE
Problems with core data

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51032-2019-Spring-Forum#23]
I'm having trouble creating/saving a new record within the core data "context" and then accessing the newly created record. Ideally I'd like to return a "WorkoutRecord" from a context block (see `saveWorkoutRecord` method  of `WorkoutsOfTypeViewController`, but clearly that isn't possible. Most of the documentation seems to only access/fetch records in the context of a `TableView`, but that doesn't work when I'm creating a new record and want to assign/access it immediately, so I don't know how to approach this.

**Comment by susanstevens** [comment]
If you just want to fetch one object you could use the fetch method (https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506672-fetch) and set the fetch request’s fetchLimit property to 1.

Another alternative would be to use “performBlockAndWait” (https://developer.apple.com/documentation/coredata/nsmanagedobjectcontext/1506364-performandwait) instead of “perform” when you create and save the workout. That way you could store the new workout to a variable outside of the block, and use it when the block exits. I’m not sure if that would have negative performance implications here, though.

Lastly, you might want to consider using NSFetchedResultsController and it’s delegate methods here, since the workouts are displayed in a table (or collection) view. That was my original intent when I wrote up the assignment, although it’s certainly not the only approach that would work.
