### ISSUE TITLE
Error fetching class from file

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51032-2019-Spring-Forum#34]
I'm working on persisting data from an extension to my app using the document directory. I've created an app group just like in assignment 1. When trying to load data from the app that has been stored by the extension (or vice versa) I get the following error: 

```Error fetching evaluations from file: Error Domain=NSCocoaErrorDomain Code=4864 "*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (FakeOut.Evaluation) for key (NS.objects); the class may be defined in source code or a library that is not linked" UserInfo={NSDebugDescription=*** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (FakeOut.Evaluation) for key (NS.objects); the class may be defined in source code or a library that is not linked}```

I've tried this: https://stackoverflow.com/questions/37028194/cannot-decode-object-of-class-employee-for-key-ns-object-0-the-class-may-be-d/51984298 but to no avail.

Any ideas here? Latest code is in `development`.

**Comment by susanstevens** [comment]
This is the key part of the error message: `the class may be defined in source code or a library that is not linked`. This is telling you that the current target (the action extension) doesn't know about the class you're trying to unarchive (`FakeOut.Evaluation`).

Since you added the `Evaluation` class to both targets, they each get their own copy of the class: `FakeOut.Evaluation` belongs to the app and `FakeOutExtension.Evaluation` belongs to the extension. So when you archive an `Evaluation` object in the app, the type being archived is actually `FakeOut.Evaluation`. The extension tried to unarchive that object, but it doesn't know about any type called `FakeOut.Evaluation`. It only knows about `FakeOutExtension.Evaluation`, which is an entirely different class.

There are two solutions here.

**Solution 1**: Create a framework and add `Evaluation` to the framework. Then, import the framework into the app and the extension so that both have access to the _same_ type: `FakeOutFramework.Evaluation`.

**Solution 2**: Add the annotation `@objc(Evaluation)` on the line above `class Evaluation`. This tells Swift not to do its usual namespacing when it exposes the class to Objective C (which is what happens when you archive and unarchive instances of the class). Instead, the class name is just `Evaluation`, regardless of whether it's referenced by the app or the extension.

(The second solution is mentioned in the StackOverflow post you linked to. If you tried that and it didn't work, did you get a different error message?)

**Comment by lmnoel** [comment]
Solved! (I didn't make it down to the second solution in the SO post, but that did indeed solve it).
