### ISSUE TITLE
Is it acceptable form to mark methods/variable inline for testing purposes that should otherwise be private

### ISSUE THREAD

**Issue by lmnoel** [uchicago-mobi/MPCS51032-2019-Spring-Forum#36]
As the title suggests, is it considered acceptable to mark methods and variables as internal to enable better unit testing that should otherwise be private?

**Comment by susanstevens** [comment]
Good question! Making private methods and properties as internal in order to test them is generally considered an anti-pattern. Think of it this way - the function signatures of a class's internal or public methods are like its interface in Swift. Everything else is part of the class's implementation. Code that relies on the class doesn't care how the class's functionality is implemented, and one reason to write unit tests is so that you can refactor the implementation (without changing the interface) and have confidence that the class's functionality hasn't changed.

(As a side note, there will be times when you need to change the interface and/or modify the actual behavior of the class. In those cases, you want to change the tests _first_ and the class itself second if you're practicing TDD.)

If you find yourself needing to change the access level of a method or property in order to test the class, it's a sign that either your tests or the class itself need to be restructured. You should be able to test the private methods indirectly by testing the internal methods.

Here's a good Quora post on the topic: https://www.quora.com/Should-you-unit-test-private-methods-on-a-class.

**Comment by lmnoel** [comment]
Thank you, that's super helpful. That was my gut reaction, but I also felt that testing my Evaluation class (with mildly complicated logic) by only checking the end result instead of the intermediate results was insufficient. I don't think an additional level of indirection is necessary in my case, so I'll just focus on testing the end results of my existing interface.
