### ISSUE TITLE
Extension Read from FileManager

### ISSUE THREAD

**Issue by jarofmy** [uchicago-mobi/MPCS51032-2019-Spring-Forum#8]
I'm able to use FileManager to write and retrieve notes within the app, however I am having a difficult time trying to get the TodayExtension to read from the FileManager. 

In the app, I am able to implement the following logic to properly retrieve a NoteItem from the FileManager:
```
let baseURL = try! FileManager.default.url(for: .documentDirectory, in: .userDomainMask, appropriateFor: nil, create: false)
fileURL = baseURL.appendingPathComponent("notes.txt")

if let data = FileManager.default.contents(atPath: fileURL.path) {
   let decoder = JSONDecoder()
   do {
          noteItems = try decoder.decode([NoteItem].self, from: data)
   } catch {
         print(error)
   }
}
```

However, when I try to do the same thing within the TodayExtensionViewController's func viewDidAppear, get "Use of unresolved identifier 'NoteItem' "

From digging around, it seems some implementations create and include a separate framework, in order to include in the today extension, but that seems a little overkill, as the today extension would only need to recognize the NoteItem model object right?

**Comment by susanstevens** [comment]
Creating a framework is Apple's recommended solution for sharing files between apps and extensions. In the WeatherWidget app, you'll notice that their framework has the `Weather` model as well as the `WeatherForecast` (essentially a service for saving to the shared Documents Directory). Image assets that are used by both the app and the extension are also included in the framework.

Another option would be to put the `NoteItem` file in your main app, but also add it to the extension target. If you open the FileInspector in the right-hand panel in Xcode, you'll see a "Target Membership" section where you can select the targets a file should be included in. Unlike the framework approach, where there is just one `NoteItem` type shared by both the app and the extension, this approach essentially creates TWO `NoteItem` types when you build the project, one for the app and one for the extension. It's as if you were to create `MyApp.NoteItem` (which the app knows about) and `MyExtension.NoteItem` (which the extension knows about).

The challenge with this approach is that when you archive an instance of `MyApp.NoteItem` to save it from the app, you can't unarchive it as an instance of `MyExtension.NoteItem` in the extension, since they are literally two different types. There are ways to work around this issues, but I'll leave that to you to figure out if you decide to take that approach.

**Comment by susanstevens** [comment]
Also make sure that you're using the correct url to the **shared** Documents Directory (not the app's individual Documents Directory, which the extension does not have access to). 🙂

**Comment by jarofmy** [comment]
> Also make sure that you're using the correct url to the **shared** Documents Directory (not the app's individual Documents Directory, which the extension does not have access to). 🙂

Thank you!

Incredible save, approaching the witching hour!
